version: '3.9'
services:
  client:
    build: ./client
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/node/app

  server:
    build: ./server
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 5000:5000
    volumes:
      - ./server:/home/node/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: notes_app
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data